;;; SPDX-License-Identifier: AGPL-3.0-only
;;; Copyright (c) 2026 Cristian Cezar Moisés — AGPL-3.0-only
;;; Build:    guix build   -f packaging/guix.scm
;;; Install:  guix package -f packaging/guix.scm
;;;
;;; Installs the pure-Python daemon, launcher, systemd unit, polkit policy,
;;; desktop entry and docs into a Guix profile.  Unlike the FHS packages
;;; (deb/rpm/Arch), whose /usr/bin shims rely on a system python3 on PATH, the
;;; Guix build rewrites both shims to call the store python3 and prepends the
;;; store paths of the tools the root daemon shells out to (iptables, chattr,
;;; tor) — so the package is self-contained and needs nothing on the profile's
;;; PATH but the inherited system tools (systemctl, xdg-open).

(use-modules (guix packages)
             (guix build-system copy)
             (guix gexp)
             (srfi srfi-13)                       ;string-contains, string-suffix?
             (gnu packages python)
             (gnu packages tor)
             (gnu packages linux)                 ;iptables, e2fsprogs (chattr)
             ((guix licenses) #:prefix license:))

(define %source
  ;; The repository root, two levels up from this file.
  (dirname (dirname (current-filename))))

(define (source-file? file stat)
  ;; Keep the source tree lean and reproducible: skip release artifacts, VCS
  ;; metadata and build/test caches so the store item (and its hash) tracks the
  ;; actual sources only.
  (not (or (string-contains file "/.git")
           (string-contains file "/dist")
           (string-contains file "/build")
           (string-contains file "/__pycache__")
           (string-contains file "/.pytest_cache")
           (string-contains file "/.ruff_cache")
           (string-suffix? ".pyc" file))))

(package
  (name "torando-gui")
  (version "1.3.4")
  (source (local-file %source "torando-gui-checkout"
                      #:recursive? #t
                      #:select? source-file?))
  (build-system copy-build-system)
  (arguments
   (list
    #:install-plan
    #~'(("backend/torando_gui" "lib/torando-gui/torando_gui")
        ("packaging/bin/torando-gui"  "bin/torando-gui")
        ("packaging/bin/torando-guid" "bin/torando-guid")
        ("packaging/systemd/torando-gui.service"
         "lib/systemd/system/torando-gui.service")
        ("packaging/polkit/co.securityops.torando-gui.policy"
         "share/polkit-1/actions/co.securityops.torando-gui.policy")
        ("packaging/polkit/49-torando-gui.rules"
         "share/polkit-1/rules.d/49-torando-gui.rules")
        ("packaging/desktop/torando-gui.desktop"
         "share/applications/torando-gui.desktop")
        ("README.md"       "share/doc/torando-gui/README.md")
        ("THREAT_MODEL.md" "share/doc/torando-gui/THREAT_MODEL.md")
        ("LICENSE"         "share/doc/torando-gui/LICENSE"))
    #:phases
    #~(modify-phases %standard-phases
        ;; No ELF payload (pure Python + /bin/sh shims): nothing to strip or
        ;; validate.
        (delete 'strip)
        (delete 'validate-runpath)
        (add-after 'install 'wrap-shims
          (lambda* (#:key inputs outputs #:allow-other-keys)
            (let* ((out    (assoc-ref outputs "out"))
                   (lib    (string-append out "/lib/torando-gui"))
                   (python (string-append (assoc-ref inputs "python") "/bin/python3"))
                   ;; Tools the root daemon execs. Prepended to PATH; the
                   ;; inherited system PATH (systemctl, xdg-open) is preserved.
                   (path   (string-join
                            (list (string-append (assoc-ref inputs "python") "/bin")
                                  (string-append (assoc-ref inputs "iptables") "/sbin")
                                  (string-append (assoc-ref inputs "iptables") "/bin")
                                  (string-append (assoc-ref inputs "e2fsprogs") "/sbin")
                                  (string-append (assoc-ref inputs "e2fsprogs") "/bin")
                                  (string-append (assoc-ref inputs "tor") "/bin"))
                            ":")))
              (define (write-shim name module)
                (let ((p (string-append out "/bin/" name)))
                  (call-with-output-file p
                    (lambda (port)
                      (format port "#!/bin/sh
# Generated by guix.scm: self-contained launcher (store python3 + tool PATH).
export PYTHONPATH=\"~a${PYTHONPATH:+:$PYTHONPATH}\"
export PATH=\"~a${PATH:+:$PATH}\"
exec ~a -m ~a \"$@\"\n"
                              lib path python module)))
                  (chmod p #o755)))
              (write-shim "torando-gui"  "torando_gui.launcher")
              (write-shim "torando-guid" "torando_gui")
              ;; Point the systemd unit at the store binary instead of /usr/bin.
              (substitute* (string-append out "/lib/systemd/system/torando-gui.service")
                (("/usr/bin/torando-guid")
                 (string-append out "/bin/torando-guid")))))))))
  (inputs (list python tor iptables e2fsprogs))
  (synopsis "Route a user's egress through Tor (transparent proxy + killswitch)")
  (description
   "Loopback web GUI that forces one local user's traffic through Tor's
TransPort and DNSPort and drops everything else from that user (a fail-closed
killswitch).  It automates the upstream torando iptables rules together with
torrc and resolv.conf management, adds an ip6tables IPv6 killswitch so v6 cannot
leak around Tor, and reports live bootstrap, DNS-leak and exit status.  This is
the Linux build; the upstream project also targets macOS, the BSDs and Windows.")
  (home-page "https://github.com/cristiancmoises/torando-gui")
  (license license:agpl3))
